# Custom toml conf
# Defined in sso-common:com.qingyou.sso.infra.config.Configuration
# feellmoose 2024.11.18
[server]
host = "0.0.0.0"
port = 8080

[database]
url = ""
user = "postgres"
password = ""
connection.poolSize = 10
[database.hibernate]
showSql = false
action = "none"

[redis]
mode = "Sentinel"
password = ""
sentinel.master = "mymaster"
sentinel.nodes = [""]
cache.ttl = 60000

[security.jwt]
secret = "
[security.cookie]
name = "session_id"
maxAge = 86_400_000
timeout = 86_400_000
path = "/sso"
domain = "feellmoose"
secure = true
httpOnly = true
[security.thirdParty]
